spring.application.name=Project-17-JDBCTemplate

spring.datasource.url=jdbc:mysql://localhost:3306/sachinsir
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

